"""add_workflows_and_transitions

Revision ID: 021c3d9ff75d
Revises: 0014_add_plans_and_task_start_date
Create Date: 2026-07-07 23:18:29.710496

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '021c3d9ff75d'
down_revision = '0014_add_plans_and_task_start_date'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_transitions',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('from_status_id', sa.Uuid(), nullable=True),
    sa.Column('to_status_id', sa.Uuid(), nullable=False),
    sa.Column('conditions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('validators', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['from_status_id'], ['custom_statuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_status_id'], ['custom_statuses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('attachments', 'size_bytes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_index(op.f('ix_board_members_board_id'), table_name='board_members')
    op.drop_index(op.f('ix_board_members_user_id'), table_name='board_members')
    op.drop_index(op.f('ix_comment_mentions_comment_id'), table_name='comment_mentions')
    op.add_column('projects', sa.Column('workflow_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'projects', 'workflows', ['workflow_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_sprints_project_id'), table_name='sprints')
    op.drop_index(op.f('ix_sprints_status'), table_name='sprints')
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sqlmodel.sql.sqltypes.AutoString(length=500),
               existing_nullable=False)
    op.drop_index(op.f('ix_tasks_issue_key'), table_name='tasks')
    op.drop_constraint(op.f('uq_tasks_issue_key'), 'tasks', type_='unique')
    op.drop_index(op.f('ix_velocity_configs_workspace_id'), table_name='velocity_configs')
    op.drop_constraint(op.f('organization_members_user_id_fkey'), 'workspace_members', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workspace_members', type_='foreignkey')
    op.create_foreign_key(op.f('organization_members_user_id_fkey'), 'workspace_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_velocity_configs_workspace_id'), 'velocity_configs', ['workspace_id'], unique=True)
    op.create_unique_constraint(op.f('uq_tasks_issue_key'), 'tasks', ['issue_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tasks_issue_key'), 'tasks', ['issue_key'], unique=True)
    op.alter_column('tasks', 'title',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_sprints_status'), 'sprints', ['status'], unique=False)
    op.create_index(op.f('ix_sprints_project_id'), 'sprints', ['project_id'], unique=False)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'workflow_id')
    op.create_index(op.f('ix_comment_mentions_comment_id'), 'comment_mentions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_board_members_user_id'), 'board_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_board_members_board_id'), 'board_members', ['board_id'], unique=False)
    op.alter_column('attachments', 'size_bytes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.drop_table('workflow_transitions')
    op.drop_table('workflows')
    # ### end Alembic commands ###
