// This file is auto-generated by @hey-api/openapi-ts

export const AuditLogPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        orgId: {
            type: 'string',
            format: 'uuid',
            title: 'Orgid'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        entityId: {
            type: 'string',
            format: 'uuid',
            title: 'Entityid'
        },
        entityType: {
            type: 'string',
            title: 'Entitytype'
        },
        entityTitle: {
            type: 'string',
            title: 'Entitytitle'
        },
        userId: {
            type: 'string',
            format: 'uuid',
            title: 'Userid'
        },
        userImage: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Userimage'
        },
        userName: {
            type: 'string',
            title: 'Username'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'orgId', 'action', 'entityId', 'entityType', 'entityTitle', 'userId', 'userName', 'createdAt', 'updatedAt'],
    title: 'AuditLogPublic',
    description: `API response for an audit log entry.

Serializes to camelCase: \`\`orgId\`\`, \`\`entityId\`\`, \`\`entityType\`\`,
\`\`entityTitle\`\`, \`\`userId\`\`, \`\`userImage\`\`, \`\`userName\`\`, \`\`createdAt\`\`,
\`\`updatedAt\`\` (requirement 8.6).`
} as const;

export const BoardCreateSchema = {
    properties: {
        orgId: {
            type: 'string',
            format: 'uuid',
            title: 'Orgid'
        },
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        imageId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imageid'
        },
        imageThumbUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagethumburl'
        },
        imageFullUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagefullurl'
        },
        imageUserName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imageusername'
        },
        imageLinkHTML: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagelinkhtml'
        }
    },
    type: 'object',
    required: ['orgId', 'title'],
    title: 'BoardCreate',
    description: `Request body for creating a board.

Accepts camelCase (\`\`orgId\`\`, \`\`imageThumbUrl\`\`, \`\`imageLinkHTML\`\`, ...) and,
thanks to \`\`populate_by_name=True\`\`, the snake_case field names too. Image
fields are optional cover-image metadata.`
} as const;

export const BoardDetailSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        orgId: {
            type: 'string',
            format: 'uuid',
            title: 'Orgid'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        imageId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imageid'
        },
        imageThumbUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagethumburl'
        },
        imageFullUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagefullurl'
        },
        imageUserName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imageusername'
        },
        imageLinkHTML: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagelinkhtml'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        },
        lists: {
            items: {
                '$ref': '#/components/schemas/ListWithCards'
            },
            type: 'array',
            title: 'Lists'
        }
    },
    type: 'object',
    required: ['id', 'orgId', 'title', 'createdAt', 'updatedAt'],
    title: 'BoardDetail',
    description: `Nested board response for \`\`GET /boards/{id}\`\` (Req 5.2).

Extends \`\`BoardPublic\`\` with \`\`lists\`\` ordered by \`\`order\`\` ascending, each
carrying its \`\`cards\`\` ordered by \`\`order\`\` ascending. The service is
responsible for loading and sorting (design.md section "3. Nested response").`
} as const;

export const BoardPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        orgId: {
            type: 'string',
            format: 'uuid',
            title: 'Orgid'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        imageId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imageid'
        },
        imageThumbUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagethumburl'
        },
        imageFullUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagefullurl'
        },
        imageUserName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imageusername'
        },
        imageLinkHTML: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagelinkhtml'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'orgId', 'title', 'createdAt', 'updatedAt'],
    title: 'BoardPublic',
    description: `Flat API response for a board (Req 5.7).

Serializes to camelCase: \`\`orgId\`\`, \`\`imageId\`\`, \`\`imageThumbUrl\`\`,
\`\`imageFullUrl\`\`, \`\`imageUserName\`\`, \`\`imageLinkHTML\`\`, \`\`createdAt\`\`,
\`\`updatedAt\`\`.`
} as const;

export const BoardUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        imageId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imageid'
        },
        imageThumbUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagethumburl'
        },
        imageFullUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagefullurl'
        },
        imageUserName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imageusername'
        },
        imageLinkHTML: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagelinkhtml'
        }
    },
    type: 'object',
    title: 'BoardUpdate',
    description: `Request body for updating a board (Req 5.3).

All fields are optional so callers can send a partial update (PATCH
semantics). Accepts camelCase (\`\`imageThumbUrl\`\`, \`\`imageLinkHTML\`\`, ...) and,
thanks to \`\`populate_by_name=True\`\`, the snake_case field names too. The
service applies only the fields that were explicitly provided
(\`\`model_dump(exclude_unset=True)\`\`). \`\`org_id\`\` is intentionally absent: a
board cannot be moved between organizations.`
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CardCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        listId: {
            type: 'string',
            format: 'uuid',
            title: 'Listid'
        }
    },
    type: 'object',
    required: ['title', 'listId'],
    title: 'CardCreate',
    description: `Request body for creating a card.

Accepts camelCase (\`\`listId\`\`) and, thanks to \`\`populate_by_name=True\`\`, the
snake_case field names too. \`\`order\`\` is NOT accepted from the client — the
service derives it as \`\`max_order(list) + 1\`\` (Req 7.1).`
} as const;

export const CardReorderSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/CardReorderItem'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['items'],
    title: 'CardReorder',
    description: `Request body for \`\`PATCH /cards/reorder\`\` (Req 7.4, 7.5, 11.1-11.4).

Carries the \`\`items\`\` whose \`\`order\`\` and \`\`listId\`\` should be applied. The
service validates that every card (resolved through its current list) and
every target \`\`listId\`\` belong to the SAME Board before applying all updates
in a single transaction.`
} as const;

export const CardReorderItemSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        order: {
            type: 'integer',
            title: 'Order'
        },
        listId: {
            type: 'string',
            format: 'uuid',
            title: 'Listid'
        }
    },
    type: 'object',
    required: ['id', 'order', 'listId'],
    title: 'CardReorderItem',
    description: `A single \`\`{id, order, listId}\`\` entry of a card reorder payload.

Unlike a list reorder entry, a card entry carries the TARGET \`\`listId\`\`
because a card can move across lists (within the same Board) during a
reorder (Req 7.4).`
} as const;

export const CardUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'CardUpdate',
    description: `Request body for \`\`PATCH /cards/{id}\`\` (Req 7.2).

\`\`title\`\` and \`\`description\`\` are optional so the client can send a partial
update; the service applies only the provided fields.`
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ListCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        boardId: {
            type: 'string',
            format: 'uuid',
            title: 'Boardid'
        }
    },
    type: 'object',
    required: ['title', 'boardId'],
    title: 'ListCreate',
    description: `Request body for creating a list.

Accepts camelCase (\`\`boardId\`\`) and, thanks to \`\`populate_by_name=True\`\`, the
snake_case field names too. \`\`order\`\` is NOT accepted from the client — the
service derives it as \`\`max_order(board) + 1\`\` (Req 6.1).`
} as const;

export const ListPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        order: {
            type: 'integer',
            title: 'Order'
        },
        boardId: {
            type: 'string',
            format: 'uuid',
            title: 'Boardid'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'title', 'order', 'boardId', 'createdAt', 'updatedAt'],
    title: 'ListPublic',
    description: `Flat API response for a list (Req 6.7).

Serializes to camelCase: \`\`boardId\`\`, \`\`createdAt\`\`, \`\`updatedAt\`\`.`
} as const;

export const ListReorderSchema = {
    properties: {
        boardId: {
            type: 'string',
            format: 'uuid',
            title: 'Boardid'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/ListReorderItem'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['boardId', 'items'],
    title: 'ListReorder',
    description: `Request body for \`\`PATCH /lists/reorder\`\` (Req 6.4, 6.5, 11.1-11.4).

Carries the target \`\`boardId\`\` and the \`\`items\`\` whose \`\`order\`\` should be
applied. The service validates that every id belongs to \`\`boardId\`\` before
touching the DB and applies all updates in a single transaction.`
} as const;

export const ListReorderItemSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        order: {
            type: 'integer',
            title: 'Order'
        }
    },
    type: 'object',
    required: ['id', 'order'],
    title: 'ListReorderItem',
    description: 'A single ``{id, order}`` entry of a reorder payload (Req 6.4).'
} as const;

export const ListUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Order'
        }
    },
    type: 'object',
    title: 'ListUpdate',
    description: `Request body for \`\`PATCH /lists/{id}\`\` (Req 6.2).

All fields are optional so the client can send a partial update; the service
applies only the provided fields.`
} as const;

export const ListWithCardsSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        order: {
            type: 'integer',
            title: 'Order'
        },
        boardId: {
            type: 'string',
            format: 'uuid',
            title: 'Boardid'
        },
        cards: {
            items: {
                '$ref': '#/components/schemas/app__schemas__boards_schema__CardPublic'
            },
            type: 'array',
            title: 'Cards'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'title', 'order', 'boardId', 'createdAt', 'updatedAt'],
    title: 'ListWithCards',
    description: `Response shape for a list with its ordered cards (frontend type \`\`List\`\`).

Serializes to camelCase: \`\`boardId\`\`, \`\`createdAt\`\`, \`\`updatedAt\`\`. \`\`cards\`\`
are expected to be ordered by \`\`order\`\` ascending by the service (Req 5.2).`
} as const;

export const OrganizationCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'OrganizationCreate',
    description: 'Request body for creating an organization.'
} as const;

export const OrganizationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'name', 'createdAt', 'updatedAt'],
    title: 'OrganizationPublic',
    description: `API response for an organization.

Serializes to camelCase: \`\`createdAt\`\`, \`\`updatedAt\`\`.`
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token',
    description: 'Access-token response for a successful login.'
} as const;

export const UserPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        fullName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fullname'
        },
        isActive: {
            type: 'boolean',
            title: 'Isactive'
        },
        isSuperuser: {
            type: 'boolean',
            title: 'Issuperuser'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'email', 'isActive', 'isSuperuser', 'createdAt', 'updatedAt'],
    title: 'UserPublic',
    description: `API response for a user — never exposes password/hashed_password.

Serializes to camelCase: \`\`fullName\`\`, \`\`isActive\`\`, \`\`isSuperuser\`\`,
\`\`createdAt\`\`, \`\`updatedAt\`\`.`
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister',
    description: 'Request body for public self-registration (``POST /users/signup``).'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const app__schemas__boards_schema__CardPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        order: {
            type: 'integer',
            title: 'Order'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        listId: {
            type: 'string',
            format: 'uuid',
            title: 'Listid'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'title', 'order', 'listId', 'createdAt', 'updatedAt'],
    title: 'CardPublic',
    description: `Response shape for a card nested under a list (frontend type \`\`Card\`\`).

Serializes to camelCase: \`\`listId\`\`, \`\`createdAt\`\`, \`\`updatedAt\`\`. This is a
response-shape definition only; the card table is owned by the task_cards
domain (task 15.1).`
} as const;

export const app__schemas__task_cards_schema__CardPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        order: {
            type: 'integer',
            title: 'Order'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        listId: {
            type: 'string',
            format: 'uuid',
            title: 'Listid'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'title', 'order', 'description', 'listId', 'createdAt', 'updatedAt'],
    title: 'CardPublic',
    description: `Flat API response for a card (Req 7.7).

Serializes to camelCase: \`\`listId\`\`, \`\`createdAt\`\`, \`\`updatedAt\`\`.`
} as const;