// This file is auto-generated by @hey-api/openapi-ts

export const ActivityLogPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        workspaceId: {
            type: 'string',
            format: 'uuid',
            title: 'Workspaceid'
        },
        projectId: {
            type: 'string',
            format: 'uuid',
            title: 'Projectid'
        },
        taskId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Taskid'
        },
        actorId: {
            type: 'string',
            format: 'uuid',
            title: 'Actorid'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        oldValue: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Oldvalue'
        },
        newValue: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Newvalue'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'workspaceId', 'projectId', 'actorId', 'action', 'createdAt', 'updatedAt'],
    title: 'ActivityLogPublic'
} as const;

export const AssigneeUpdateSchema = {
    properties: {
        assigneeId: {
            type: 'string',
            format: 'uuid',
            title: 'Assigneeid'
        }
    },
    type: 'object',
    required: ['assigneeId'],
    title: 'AssigneeUpdate'
} as const;

export const AttachmentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        taskId: {
            type: 'string',
            format: 'uuid',
            title: 'Taskid'
        },
        uploaderId: {
            type: 'string',
            format: 'uuid',
            title: 'Uploaderid'
        },
        fileName: {
            type: 'string',
            title: 'Filename'
        },
        mimeType: {
            type: 'string',
            title: 'Mimetype'
        },
        sizeBytes: {
            type: 'integer',
            title: 'Sizebytes'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        },
        uploader: {
            '$ref': '#/components/schemas/AuthorPublic'
        }
    },
    type: 'object',
    required: ['id', 'taskId', 'uploaderId', 'fileName', 'mimeType', 'sizeBytes', 'createdAt', 'updatedAt', 'uploader'],
    title: 'AttachmentPublic'
} as const;

export const AuditLogPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        orgId: {
            type: 'string',
            format: 'uuid',
            title: 'Orgid'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        entityId: {
            type: 'string',
            format: 'uuid',
            title: 'Entityid'
        },
        entityType: {
            type: 'string',
            title: 'Entitytype'
        },
        entityTitle: {
            type: 'string',
            title: 'Entitytitle'
        },
        userId: {
            type: 'string',
            format: 'uuid',
            title: 'Userid'
        },
        userImage: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Userimage'
        },
        userName: {
            type: 'string',
            title: 'Username'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'orgId', 'action', 'entityId', 'entityType', 'entityTitle', 'userId', 'userName', 'createdAt', 'updatedAt'],
    title: 'AuditLogPublic'
} as const;

export const AuthorPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        fullName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fullname'
        },
        avatarUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatarurl'
        }
    },
    type: 'object',
    required: ['id'],
    title: 'AuthorPublic',
    description: 'Public attribution for the person who performed/owns a resource.'
} as const;

export const BoardCreateSchema = {
    properties: {
        orgId: {
            type: 'string',
            format: 'uuid',
            title: 'Orgid'
        },
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        imageId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imageid'
        },
        imageThumbUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagethumburl'
        },
        imageFullUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagefullurl'
        },
        imageUserName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imageusername'
        },
        imageLinkHTML: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagelinkhtml'
        }
    },
    type: 'object',
    required: ['orgId', 'title'],
    title: 'BoardCreate'
} as const;

export const BoardDetailSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        orgId: {
            type: 'string',
            format: 'uuid',
            title: 'Orgid'
        },
        projectId: {
            type: 'string',
            format: 'uuid',
            title: 'Projectid'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        imageId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imageid'
        },
        imageThumbUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagethumburl'
        },
        imageFullUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagefullurl'
        },
        imageUserName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imageusername'
        },
        imageLinkHTML: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagelinkhtml'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        },
        lists: {
            items: {
                '$ref': '#/components/schemas/ListWithCards'
            },
            type: 'array',
            title: 'Lists'
        }
    },
    type: 'object',
    required: ['id', 'orgId', 'projectId', 'title', 'createdAt', 'updatedAt'],
    title: 'BoardDetail'
} as const;

export const BoardMemberAddSchema = {
    properties: {
        userId: {
            type: 'string',
            format: 'uuid',
            title: 'Userid'
        },
        role: {
            type: 'string',
            title: 'Role'
        }
    },
    type: 'object',
    required: ['userId', 'role'],
    title: 'BoardMemberAdd'
} as const;

export const BoardMemberPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        userId: {
            type: 'string',
            format: 'uuid',
            title: 'Userid'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        fullName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fullname'
        },
        avatarUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatarurl'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        invitedBy: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Invitedby'
        }
    },
    type: 'object',
    required: ['id', 'userId', 'email', 'fullName', 'role', 'status'],
    title: 'BoardMemberPublic'
} as const;

export const BoardMemberRoleUpdateSchema = {
    properties: {
        role: {
            type: 'string',
            title: 'Role'
        }
    },
    type: 'object',
    required: ['role'],
    title: 'BoardMemberRoleUpdate'
} as const;

export const BoardPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        orgId: {
            type: 'string',
            format: 'uuid',
            title: 'Orgid'
        },
        projectId: {
            type: 'string',
            format: 'uuid',
            title: 'Projectid'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        imageId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imageid'
        },
        imageThumbUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagethumburl'
        },
        imageFullUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagefullurl'
        },
        imageUserName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imageusername'
        },
        imageLinkHTML: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagelinkhtml'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'orgId', 'projectId', 'title', 'createdAt', 'updatedAt'],
    title: 'BoardPublic'
} as const;

export const BoardUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        imageId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imageid'
        },
        imageThumbUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagethumburl'
        },
        imageFullUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagefullurl'
        },
        imageUserName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imageusername'
        },
        imageLinkHTML: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Imagelinkhtml'
        }
    },
    type: 'object',
    title: 'BoardUpdate'
} as const;

export const Body_attachments_upload_attachmentSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_attachments-upload_attachment'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CanonicalStatusSchema = {
    type: 'string',
    enum: ['TODO', 'IN_PROGRESS', 'PENDING', 'DONE'],
    title: 'CanonicalStatus',
    description: 'Fixed system-defined statuses; not creatable or editable via any endpoint.'
} as const;

export const CardCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        listId: {
            type: 'string',
            format: 'uuid',
            title: 'Listid'
        }
    },
    type: 'object',
    required: ['title', 'listId'],
    title: 'CardCreate'
} as const;

export const CardReorderSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/CardReorderItem'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['items'],
    title: 'CardReorder'
} as const;

export const CardReorderItemSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        order: {
            type: 'integer',
            title: 'Order'
        },
        listId: {
            type: 'string',
            format: 'uuid',
            title: 'Listid'
        }
    },
    type: 'object',
    required: ['id', 'order', 'listId'],
    title: 'CardReorderItem',
    description: 'A card reorder entry carries the target listId because a card can move across lists.'
} as const;

export const CardUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'CardUpdate'
} as const;

export const ColumnCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        statusKey: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Statuskey'
        },
        position: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        }
    },
    type: 'object',
    required: ['name', 'statusKey'],
    title: 'ColumnCreate'
} as const;

export const ColumnPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        boardId: {
            type: 'string',
            format: 'uuid',
            title: 'Boardid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        statusKey: {
            type: 'string',
            title: 'Statuskey'
        },
        position: {
            type: 'integer',
            title: 'Position'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'boardId', 'name', 'statusKey', 'position', 'createdAt', 'updatedAt'],
    title: 'ColumnPublic'
} as const;

export const ColumnReorderSchema = {
    properties: {
        items: {
            items: {
                '$ref': '#/components/schemas/ColumnReorderItem'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['items'],
    title: 'ColumnReorder'
} as const;

export const ColumnReorderItemSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        position: {
            type: 'integer',
            title: 'Position'
        }
    },
    type: 'object',
    required: ['id', 'position'],
    title: 'ColumnReorderItem'
} as const;

export const ColumnUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        statusKey: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Statuskey'
        },
        position: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Position'
        }
    },
    type: 'object',
    title: 'ColumnUpdate'
} as const;

export const CommentCreateSchema = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['content'],
    title: 'CommentCreate'
} as const;

export const CommentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        taskId: {
            type: 'string',
            format: 'uuid',
            title: 'Taskid'
        },
        userId: {
            type: 'string',
            format: 'uuid',
            title: 'Userid'
        },
        content: {
            type: 'string',
            title: 'Content'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        },
        author: {
            '$ref': '#/components/schemas/AuthorPublic'
        }
    },
    type: 'object',
    required: ['id', 'taskId', 'userId', 'content', 'createdAt', 'updatedAt', 'author'],
    title: 'CommentPublic'
} as const;

export const CommentUpdateSchema = {
    properties: {
        content: {
            type: 'string',
            title: 'Content'
        }
    },
    type: 'object',
    required: ['content'],
    title: 'CommentUpdate'
} as const;

export const CustomStatusCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        canonicalStatus: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CanonicalStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['name'],
    title: 'CustomStatusCreate'
} as const;

export const CustomStatusEmbedSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        canonicalStatus: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Canonicalstatus'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'CustomStatusEmbed'
} as const;

export const CustomStatusPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        workspaceId: {
            type: 'string',
            format: 'uuid',
            title: 'Workspaceid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        canonicalStatus: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Canonicalstatus'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'workspaceId', 'name', 'color', 'canonicalStatus', 'createdAt', 'updatedAt'],
    title: 'CustomStatusPublic'
} as const;

export const CustomStatusUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        color: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Color'
        },
        canonicalStatus: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CanonicalStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'CustomStatusUpdate'
} as const;

export const EpicCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        priority: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Priority'
        },
        dueDate: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duedate'
        },
        storyPoint: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Storypoint'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'EpicCreate'
} as const;

export const EpicProgressPublicSchema = {
    properties: {
        epicId: {
            type: 'string',
            format: 'uuid',
            title: 'Epicid'
        },
        totalTasks: {
            type: 'integer',
            title: 'Totaltasks'
        },
        completedTasks: {
            type: 'integer',
            title: 'Completedtasks'
        },
        storyPointsTotal: {
            type: 'integer',
            title: 'Storypointstotal'
        },
        storyPointsCompleted: {
            type: 'integer',
            title: 'Storypointscompleted'
        },
        completionPercentage: {
            type: 'number',
            title: 'Completionpercentage'
        }
    },
    type: 'object',
    required: ['epicId', 'totalTasks', 'completedTasks', 'storyPointsTotal', 'storyPointsCompleted', 'completionPercentage'],
    title: 'EpicProgressPublic'
} as const;

export const EpicPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        projectId: {
            type: 'string',
            format: 'uuid',
            title: 'Projectid'
        },
        boardId: {
            type: 'string',
            format: 'uuid',
            title: 'Boardid'
        },
        columnId: {
            type: 'string',
            format: 'uuid',
            title: 'Columnid'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        priority: {
            type: 'string',
            title: 'Priority'
        },
        dueDate: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duedate'
        },
        assigneeId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assigneeid'
        },
        customStatusId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customstatusid'
        },
        position: {
            type: 'integer',
            title: 'Position'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        storyPoint: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Storypoint'
        },
        sprintId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sprintid'
        },
        epicId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Epicid'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'projectId', 'boardId', 'columnId', 'title', 'description', 'priority', 'dueDate', 'assigneeId', 'customStatusId', 'position', 'type', 'storyPoint', 'sprintId', 'epicId', 'createdAt', 'updatedAt'],
    title: 'EpicPublic'
} as const;

export const EpicUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        priority: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Priority'
        },
        dueDate: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duedate'
        },
        storyPoint: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Storypoint'
        }
    },
    type: 'object',
    title: 'EpicUpdate'
} as const;

export const EpicWithTasksPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        projectId: {
            type: 'string',
            format: 'uuid',
            title: 'Projectid'
        },
        boardId: {
            type: 'string',
            format: 'uuid',
            title: 'Boardid'
        },
        columnId: {
            type: 'string',
            format: 'uuid',
            title: 'Columnid'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        priority: {
            type: 'string',
            title: 'Priority'
        },
        dueDate: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duedate'
        },
        assigneeId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assigneeid'
        },
        customStatusId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customstatusid'
        },
        position: {
            type: 'integer',
            title: 'Position'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        storyPoint: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Storypoint'
        },
        sprintId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sprintid'
        },
        epicId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Epicid'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        },
        childTasks: {
            items: {
                '$ref': '#/components/schemas/TaskPublic'
            },
            type: 'array',
            title: 'Childtasks',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'projectId', 'boardId', 'columnId', 'title', 'description', 'priority', 'dueDate', 'assigneeId', 'customStatusId', 'position', 'type', 'storyPoint', 'sprintId', 'epicId', 'createdAt', 'updatedAt'],
    title: 'EpicWithTasksPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InvitationPublicSchema = {
    properties: {
        membershipId: {
            type: 'string',
            format: 'uuid',
            title: 'Membershipid'
        },
        scope: {
            type: 'string',
            enum: ['WORKSPACE', 'PROJECT'],
            title: 'Scope'
        },
        workspaceId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workspaceid'
        },
        projectId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Projectid'
        },
        orgName: {
            type: 'string',
            title: 'Orgname'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        invitedBy: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Invitedby'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        }
    },
    type: 'object',
    required: ['membershipId', 'scope', 'orgName', 'role', 'createdAt'],
    title: 'InvitationPublic'
} as const;

export const ListCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        boardId: {
            type: 'string',
            format: 'uuid',
            title: 'Boardid'
        }
    },
    type: 'object',
    required: ['title', 'boardId'],
    title: 'ListCreate'
} as const;

export const ListPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        order: {
            type: 'integer',
            title: 'Order'
        },
        boardId: {
            type: 'string',
            format: 'uuid',
            title: 'Boardid'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'title', 'order', 'boardId', 'createdAt', 'updatedAt'],
    title: 'ListPublic'
} as const;

export const ListReorderSchema = {
    properties: {
        boardId: {
            type: 'string',
            format: 'uuid',
            title: 'Boardid'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/ListReorderItem'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['boardId', 'items'],
    title: 'ListReorder'
} as const;

export const ListReorderItemSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        order: {
            type: 'integer',
            title: 'Order'
        }
    },
    type: 'object',
    required: ['id', 'order'],
    title: 'ListReorderItem'
} as const;

export const ListUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Order'
        }
    },
    type: 'object',
    title: 'ListUpdate'
} as const;

export const ListWithCardsSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        order: {
            type: 'integer',
            title: 'Order'
        },
        boardId: {
            type: 'string',
            format: 'uuid',
            title: 'Boardid'
        },
        cards: {
            items: {
                '$ref': '#/components/schemas/app__schemas__boards_schema__CardPublic'
            },
            type: 'array',
            title: 'Cards'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'title', 'order', 'boardId', 'createdAt', 'updatedAt'],
    title: 'ListWithCards'
} as const;

export const MappingSummarySchema = {
    properties: {
        total: {
            type: 'integer',
            title: 'Total'
        },
        mapped: {
            type: 'integer',
            title: 'Mapped'
        },
        unmapped: {
            type: 'integer',
            title: 'Unmapped'
        },
        byCanonical: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Bycanonical'
        }
    },
    type: 'object',
    required: ['total', 'mapped', 'unmapped'],
    title: 'MappingSummary'
} as const;

export const MappingUpdateSchema = {
    properties: {
        canonicalStatus: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CanonicalStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'MappingUpdate'
} as const;

export const MemberAddSchema = {
    properties: {
        userId: {
            type: 'string',
            format: 'uuid',
            title: 'Userid'
        },
        projectRole: {
            type: 'string',
            title: 'Projectrole'
        }
    },
    type: 'object',
    required: ['userId', 'projectRole'],
    title: 'MemberAdd'
} as const;

export const MemberRoleUpdateSchema = {
    properties: {
        projectRole: {
            type: 'string',
            title: 'Projectrole'
        }
    },
    type: 'object',
    required: ['projectRole'],
    title: 'MemberRoleUpdate'
} as const;

export const NotificationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        type: {
            type: 'string',
            title: 'Type'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        metadata: {
            anyOf: [
                {
                    additionalProperties: true,
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Metadata'
        },
        isRead: {
            type: 'boolean',
            title: 'Isread'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        }
    },
    type: 'object',
    required: ['id', 'type', 'title', 'isRead', 'createdAt'],
    title: 'NotificationPublic'
} as const;

export const OrganizationCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'OrganizationCreate'
} as const;

export const OrganizationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'name', 'createdAt', 'updatedAt'],
    title: 'OrganizationPublic'
} as const;

export const ProjectCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        key: {
            type: 'string',
            maxLength: 20,
            minLength: 1,
            title: 'Key'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['name', 'key'],
    title: 'ProjectCreate'
} as const;

export const ProjectMemberPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        userId: {
            type: 'string',
            format: 'uuid',
            title: 'Userid'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        fullName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fullname'
        },
        avatarUrl: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatarurl'
        },
        projectRole: {
            type: 'string',
            title: 'Projectrole'
        },
        status: {
            type: 'string',
            title: 'Status'
        }
    },
    type: 'object',
    required: ['id', 'userId', 'email', 'fullName', 'projectRole', 'status'],
    title: 'ProjectMemberPublic'
} as const;

export const ProjectPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        workspaceId: {
            type: 'string',
            format: 'uuid',
            title: 'Workspaceid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        key: {
            type: 'string',
            title: 'Key'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        createdBy: {
            type: 'string',
            format: 'uuid',
            title: 'Createdby'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'workspaceId', 'name', 'key', 'description', 'createdBy', 'createdAt', 'updatedAt'],
    title: 'ProjectPublic'
} as const;

export const SprintCompleteSchema = {
    properties: {
        moveOpenTo: {
            type: 'string',
            title: 'Moveopento',
            default: 'backlog'
        }
    },
    type: 'object',
    title: 'SprintComplete'
} as const;

export const SprintCreateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        goal: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Goal'
        },
        startDate: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Startdate'
        },
        endDate: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enddate'
        }
    },
    type: 'object',
    title: 'SprintCreate'
} as const;

export const SprintInsightsSchema = {
    properties: {
        commitment: {
            additionalProperties: true,
            type: 'object',
            title: 'Commitment'
        },
        workTypes: {
            additionalProperties: true,
            type: 'object',
            title: 'Worktypes'
        }
    },
    type: 'object',
    required: ['commitment', 'workTypes'],
    title: 'SprintInsights'
} as const;

export const SprintPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        projectId: {
            type: 'string',
            format: 'uuid',
            title: 'Projectid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        goal: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Goal'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        startDate: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Startdate'
        },
        endDate: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enddate'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'projectId', 'name', 'goal', 'status', 'startDate', 'endDate', 'createdAt', 'updatedAt'],
    title: 'SprintPublic'
} as const;

export const SprintStartSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        goal: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Goal'
        },
        startDate: {
            type: 'string',
            format: 'date',
            title: 'Startdate'
        },
        endDate: {
            type: 'string',
            format: 'date',
            title: 'Enddate'
        }
    },
    type: 'object',
    required: ['startDate', 'endDate'],
    title: 'SprintStart'
} as const;

export const SprintUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        goal: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Goal'
        },
        startDate: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Startdate'
        },
        endDate: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enddate'
        }
    },
    type: 'object',
    title: 'SprintUpdate'
} as const;

export const SprintWithTasksSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        projectId: {
            type: 'string',
            format: 'uuid',
            title: 'Projectid'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        goal: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Goal'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        startDate: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Startdate'
        },
        endDate: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enddate'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        },
        tasks: {
            items: {
                '$ref': '#/components/schemas/TaskPublic'
            },
            type: 'array',
            title: 'Tasks',
            default: []
        },
        todoCount: {
            type: 'integer',
            title: 'Todocount',
            default: 0
        },
        inProgressCount: {
            type: 'integer',
            title: 'Inprogresscount',
            default: 0
        },
        doneCount: {
            type: 'integer',
            title: 'Donecount',
            default: 0
        }
    },
    type: 'object',
    required: ['id', 'projectId', 'name', 'goal', 'status', 'startDate', 'endDate', 'createdAt', 'updatedAt'],
    title: 'SprintWithTasks',
    description: 'Sprint list item — includes tasks + kanban status counts.'
} as const;

export const StoryPointUpdateSchema = {
    properties: {
        storyPoint: {
            type: 'integer',
            title: 'Storypoint'
        }
    },
    type: 'object',
    required: ['storyPoint'],
    title: 'StoryPointUpdate'
} as const;

export const TaskCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Type'
        },
        parentId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parentid'
        },
        dueDate: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duedate'
        },
        assigneeId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assigneeid'
        },
        storyPoint: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Storypoint'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'TaskCreate'
} as const;

export const TaskPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        projectId: {
            type: 'string',
            format: 'uuid',
            title: 'Projectid'
        },
        boardId: {
            type: 'string',
            format: 'uuid',
            title: 'Boardid'
        },
        columnId: {
            type: 'string',
            format: 'uuid',
            title: 'Columnid'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        priority: {
            type: 'string',
            title: 'Priority'
        },
        dueDate: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duedate'
        },
        assigneeId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assigneeid'
        },
        customStatusId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customstatusid'
        },
        customStatus: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CustomStatusEmbed'
                },
                {
                    type: 'null'
                }
            ]
        },
        position: {
            type: 'integer',
            title: 'Position'
        },
        type: {
            type: 'string',
            title: 'Type',
            default: 'TASK'
        },
        storyPoint: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Storypoint'
        },
        sprintId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sprintid'
        },
        epicId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Epicid'
        },
        parentId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parentid'
        },
        issueKey: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Issuekey'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'projectId', 'boardId', 'columnId', 'title', 'description', 'priority', 'dueDate', 'assigneeId', 'customStatusId', 'position', 'createdAt', 'updatedAt'],
    title: 'TaskPublic'
} as const;

export const TaskUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        priority: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Priority'
        },
        dueDate: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duedate'
        },
        assigneeId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Assigneeid'
        },
        customStatusId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customstatusid'
        },
        columnId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Columnid'
        },
        type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Type'
        },
        storyPoint: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Storypoint'
        },
        sprintId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sprintid'
        },
        epicId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Epicid'
        },
        parentId: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parentid'
        }
    },
    type: 'object',
    title: 'TaskUpdate',
    description: 'Partial update payload; only explicitly provided fields are applied.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token',
    description: 'Access-token response for a successful login.'
} as const;

export const UnreadCountPublicSchema = {
    properties: {
        unreadCount: {
            type: 'integer',
            title: 'Unreadcount'
        }
    },
    type: 'object',
    required: ['unreadCount'],
    title: 'UnreadCountPublic'
} as const;

export const UserPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        fullName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fullname'
        },
        isActive: {
            type: 'boolean',
            title: 'Isactive'
        },
        isSuperuser: {
            type: 'boolean',
            title: 'Issuperuser'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'email', 'isActive', 'isSuperuser', 'createdAt', 'updatedAt'],
    title: 'UserPublic',
    description: 'API response for a user — never exposes password/hashed_password.'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister',
    description: 'Request body for public self-registration (``POST /users/signup``).'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const VelocityConfigPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        workspaceId: {
            type: 'string',
            format: 'uuid',
            title: 'Workspaceid'
        },
        hoursPerPoint: {
            type: 'number',
            title: 'Hoursperpoint'
        }
    },
    type: 'object',
    required: ['id', 'workspaceId', 'hoursPerPoint'],
    title: 'VelocityConfigPublic'
} as const;

export const VelocityConfigUpdateSchema = {
    properties: {
        hoursPerPoint: {
            type: 'number',
            title: 'Hoursperpoint'
        }
    },
    type: 'object',
    required: ['hoursPerPoint'],
    title: 'VelocityConfigUpdate'
} as const;

export const WorkspaceInviteSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        role: {
            type: 'string',
            title: 'Role'
        }
    },
    type: 'object',
    required: ['email', 'role'],
    title: 'WorkspaceInvite'
} as const;

export const WorkspaceMemberPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        workspaceId: {
            type: 'string',
            format: 'uuid',
            title: 'Workspaceid'
        },
        userId: {
            type: 'string',
            format: 'uuid',
            title: 'Userid'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        fullName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fullname'
        },
        role: {
            type: 'string',
            title: 'Role'
        },
        status: {
            type: 'string',
            title: 'Status'
        },
        invitedBy: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Invitedby'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'workspaceId', 'userId', 'email', 'role', 'status', 'createdAt', 'updatedAt'],
    title: 'WorkspaceMemberPublic'
} as const;

export const WorkspaceModeUpdateSchema = {
    properties: {
        mode: {
            type: 'string',
            title: 'Mode'
        }
    },
    type: 'object',
    required: ['mode'],
    title: 'WorkspaceModeUpdate'
} as const;

export const app__schemas__boards_schema__CardPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        order: {
            type: 'integer',
            title: 'Order'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        listId: {
            type: 'string',
            format: 'uuid',
            title: 'Listid'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'title', 'order', 'listId', 'createdAt', 'updatedAt'],
    title: 'CardPublic'
} as const;

export const app__schemas__task_cards_schema__CardPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        order: {
            type: 'integer',
            title: 'Order'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        listId: {
            type: 'string',
            format: 'uuid',
            title: 'Listid'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: ['id', 'title', 'order', 'description', 'listId', 'createdAt', 'updatedAt'],
    title: 'CardPublic'
} as const;