// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { AuditLogsListOrgAuditLogsData, AuditLogsListOrgAuditLogsResponse, AuditLogsListBoardAuditLogsData, AuditLogsListBoardAuditLogsResponse, AuditLogsListCardAuditLogsData, AuditLogsListCardAuditLogsResponse, BoardsCreateBoardData, BoardsCreateBoardResponse, BoardsListBoardsData, BoardsListBoardsResponse, BoardsGetBoardData, BoardsGetBoardResponse, BoardsUpdateBoardData, BoardsUpdateBoardResponse, BoardsDeleteBoardData, BoardsDeleteBoardResponse, CardsCreateCardData, CardsCreateCardResponse, CardsReorderCardsData, CardsReorderCardsResponse, CardsUpdateCardData, CardsUpdateCardResponse, CardsDeleteCardData, CardsDeleteCardResponse, CardsCopyCardData, CardsCopyCardResponse, ListsCreateListData, ListsCreateListResponse, ListsReorderListsData, ListsReorderListsResponse, ListsUpdateListData, ListsUpdateListResponse, ListsDeleteListData, ListsDeleteListResponse, ListsCopyListData, ListsCopyListResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, OrganizationsListOrganizationsResponse, OrganizationsCreateOrganizationData, OrganizationsCreateOrganizationResponse, OrganizationsGetOrganizationData, OrganizationsGetOrganizationResponse, UsersSignupData, UsersSignupResponse, UsersReadCurrentUserResponse } from './types.gen';

export class AuditLogsService {
    /**
     * List Org Audit Logs
     * List an organization's audit log, newest first, paginated (Req 8.3).
     *
     * Requires ``orgId``; enforces org-scoping (HTTP 403 "Not a member of this
     * organization" for non-members). Pages via ``skip`` / ``limit``.
     * @param data The data for the request.
     * @param data.orgId
     * @param data.skip
     * @param data.limit
     * @returns AuditLogPublic Successful Response
     * @throws ApiError
     */
    public static AuditLogs_auditLogsListOrgAuditLogs(data: AuditLogsListOrgAuditLogsData): CancelablePromise<AuditLogsListOrgAuditLogsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/audit-logs',
            query: {
                orgId: data.orgId,
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Board Audit Logs
     * List a board's audit log, newest first (Req 8.4).
     *
     * Returns HTTP 404 when the board does not exist and HTTP 403 when the current
     * user is not a member of the owning organization.
     * @param data The data for the request.
     * @param data.boardId
     * @returns AuditLogPublic Successful Response
     * @throws ApiError
     */
    public static AuditLogs_auditLogsListBoardAuditLogs(data: AuditLogsListBoardAuditLogsData): CancelablePromise<AuditLogsListBoardAuditLogsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/boards/{board_id}/audit-logs',
            path: {
                board_id: data.boardId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Card Audit Logs
     * List a card's audit log, newest first (Req 8.5).
     *
     * Enforces org-scoping (HTTP 403 for non-members of the card's organization).
     * @param data The data for the request.
     * @param data.cardId
     * @returns AuditLogPublic Successful Response
     * @throws ApiError
     */
    public static AuditLogs_auditLogsListCardAuditLogs(data: AuditLogsListCardAuditLogsData): CancelablePromise<AuditLogsListCardAuditLogsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/cards/{card_id}/audit-logs',
            path: {
                card_id: data.cardId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class BoardsService {
    /**
     * Create Board
     * Create a board for an organization the current user is a member of.
     *
     * Delegates to ``BoardsService.create_board`` which enforces org-membership
     * (HTTP 403 for non-members), the free-tier cap (HTTP 403 "Free tier board
     * limit reached"), increments ``OrgLimit.count`` and records a CREATE audit row
     * — all atomically (Req 5.1, 5.5, 5.6, 8.1). Returns ``BoardPublic``.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns BoardPublic Successful Response
     * @throws ApiError
     */
    public static Boards_boardsCreateBoard(data: BoardsCreateBoardData): CancelablePromise<BoardsCreateBoardResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/boards',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Boards
     * List the boards of an organization the current user is a member of.
     *
     * Requires ``orgId``; enforces org-scoping via ``BoardsService.list_boards``
     * (HTTP 403 "Not a member of this organization" for non-members — Req 4).
     * @param data The data for the request.
     * @param data.orgId
     * @returns BoardPublic Successful Response
     * @throws ApiError
     */
    public static Boards_boardsListBoards(data: BoardsListBoardsData): CancelablePromise<BoardsListBoardsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/boards',
            query: {
                orgId: data.orgId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Board
     * Return a board with its lists and cards nested, ascending by ``order``.
     *
     * Delegates to ``BoardsService.get_board_detail`` which enforces org-scoping
     * (HTTP 403 for non-members), returns HTTP 404 when the board does not exist,
     * and orders ``lists`` and each list's ``cards`` ascending by ``order``
     * (Req 5.2).
     * @param data The data for the request.
     * @param data.boardId
     * @returns BoardDetail Successful Response
     * @throws ApiError
     */
    public static Boards_boardsGetBoard(data: BoardsGetBoardData): CancelablePromise<BoardsGetBoardResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/boards/{board_id}',
            path: {
                board_id: data.boardId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Board
     * Apply a partial update to a board and return it (Req 5.3).
     *
     * Delegates to ``BoardsService.update_board`` which enforces org-scoping
     * (HTTP 403 for non-members), returns HTTP 404 when the board does not exist,
     * applies only the provided fields and records an UPDATE audit row.
     * @param data The data for the request.
     * @param data.boardId
     * @param data.requestBody
     * @returns BoardPublic Successful Response
     * @throws ApiError
     */
    public static Boards_boardsUpdateBoard(data: BoardsUpdateBoardData): CancelablePromise<BoardsUpdateBoardResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/boards/{board_id}',
            path: {
                board_id: data.boardId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Board
     * Delete a board and its descendants, returning HTTP 204 (Req 5.4).
     *
     * Delegates to ``BoardsService.delete_board`` which enforces org-scoping
     * (HTTP 403 for non-members), returns HTTP 404 when the board does not exist,
     * cascades the delete to the board's lists/cards, decrements ``OrgLimit.count``
     * and records a DELETE audit row — all atomically.
     * @param data The data for the request.
     * @param data.boardId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static Boards_boardsDeleteBoard(data: BoardsDeleteBoardData): CancelablePromise<BoardsDeleteBoardResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/boards/{board_id}',
            path: {
                board_id: data.boardId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class CardsService {
    /**
     * Create Card
     * Create a card at the end of its list (Req 7.1).
     *
     * Delegates to ``TaskCardsService.create_card`` which enforces org-membership
     * (HTTP 403 for non-members), returns HTTP 404 "List not found" / "Board not
     * found" when the owning list/board does not exist, derives ``order`` =
     * ``max_order(list) + 1`` and records a CREATE audit row — all atomically.
     * Returns ``CardPublic``.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns app__schemas__task_cards_schema__CardPublic Successful Response
     * @throws ApiError
     */
    public static Cards_cardsCreateCard(data: CardsCreateCardData): CancelablePromise<CardsCreateCardResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/cards',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reorder Cards
     * Atomically apply a new ``order`` (and target list) to a set of cards
     * (Req 7.4).
     *
     * Declared BEFORE ``/cards/{card_id}`` so ``reorder`` is matched as a literal
     * path and not captured as a ``card_id``. Delegates to
     * ``TaskCardsService.reorder_cards`` (forwarding ``data.items``) which enforces
     * org-membership (HTTP 403), validates that every card and every target list
     * belong to the same Board before touching the DB (HTTP 400 "Invalid reorder
     * payload") and applies all updates in a single transaction. Returns the
     * updated ``list[CardPublic]``.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns app__schemas__task_cards_schema__CardPublic Successful Response
     * @throws ApiError
     */
    public static Cards_cardsReorderCards(data: CardsReorderCardsData): CancelablePromise<CardsReorderCardsResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/cards/reorder',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Card
     * Apply a partial update to a card and return it (Req 7.2).
     *
     * Delegates to ``TaskCardsService.update_card`` which enforces org-membership
     * (HTTP 403 for non-members), returns HTTP 404 "Card not found" when the card
     * does not exist, applies only the provided fields and records an UPDATE audit
     * row.
     * @param data The data for the request.
     * @param data.cardId
     * @param data.requestBody
     * @returns app__schemas__task_cards_schema__CardPublic Successful Response
     * @throws ApiError
     */
    public static Cards_cardsUpdateCard(data: CardsUpdateCardData): CancelablePromise<CardsUpdateCardResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/cards/{card_id}',
            path: {
                card_id: data.cardId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Card
     * Delete a card, returning HTTP 204 (Req 7.3).
     *
     * Delegates to ``TaskCardsService.delete_card`` which enforces org-membership
     * (HTTP 403 for non-members), returns HTTP 404 "Card not found" when the card
     * does not exist, records a DELETE audit row and removes the card — all
     * atomically.
     * @param data The data for the request.
     * @param data.cardId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static Cards_cardsDeleteCard(data: CardsDeleteCardData): CancelablePromise<CardsDeleteCardResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/cards/{card_id}',
            path: {
                card_id: data.cardId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Copy Card
     * Duplicate a card within the same list (Req 7.6).
     *
     * Delegates to ``TaskCardsService.copy_card`` which enforces org-membership
     * (HTTP 403 for non-members), returns HTTP 404 "Card not found" when the card
     * does not exist, appends the copy at the end of the same list (title
     * ``"{source} - Copy"``, copying the description) and records a CREATE audit
     * row — all atomically. Returns the new ``CardPublic``.
     * @param data The data for the request.
     * @param data.cardId
     * @returns app__schemas__task_cards_schema__CardPublic Successful Response
     * @throws ApiError
     */
    public static Cards_cardsCopyCard(data: CardsCopyCardData): CancelablePromise<CardsCopyCardResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/cards/{card_id}/copy',
            path: {
                card_id: data.cardId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ListsService {
    /**
     * Create List
     * Create a list at the end of its board (Req 6.1).
     *
     * Delegates to ``BoardListsService.create_list`` which enforces org-membership
     * (HTTP 403 for non-members), returns HTTP 404 "Board not found" when the
     * board does not exist, derives ``order`` = ``max_order(board) + 1`` and
     * records a CREATE audit row — all atomically. Returns ``ListPublic``.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ListPublic Successful Response
     * @throws ApiError
     */
    public static Lists_listsCreateList(data: ListsCreateListData): CancelablePromise<ListsCreateListResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/lists',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reorder Lists
     * Atomically apply a new ``order`` to every list of a board (Req 6.4).
     *
     * Declared BEFORE ``/lists/{list_id}`` so ``reorder`` is matched as a literal
     * path and not captured as a ``list_id``. Delegates to
     * ``BoardListsService.reorder_lists`` which enforces org-membership (HTTP 403),
     * validates the payload before touching the DB (HTTP 400 "Invalid reorder
     * payload") and applies all updates in a single transaction. Returns the
     * updated ``list[ListPublic]``.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ListPublic Successful Response
     * @throws ApiError
     */
    public static Lists_listsReorderLists(data: ListsReorderListsData): CancelablePromise<ListsReorderListsResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/lists/reorder',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update List
     * Apply a partial update to a list and return it (Req 6.2).
     *
     * Delegates to ``BoardListsService.update_list`` which enforces org-membership
     * (HTTP 403 for non-members), returns HTTP 404 "List not found" when the list
     * does not exist, applies only the provided fields and records an UPDATE audit
     * row.
     * @param data The data for the request.
     * @param data.listId
     * @param data.requestBody
     * @returns ListPublic Successful Response
     * @throws ApiError
     */
    public static Lists_listsUpdateList(data: ListsUpdateListData): CancelablePromise<ListsUpdateListResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/lists/{list_id}',
            path: {
                list_id: data.listId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete List
     * Delete a list and its cards, returning HTTP 204 (Req 6.3).
     *
     * Delegates to ``BoardListsService.delete_list`` which enforces org-membership
     * (HTTP 403 for non-members), returns HTTP 404 "List not found" when the list
     * does not exist, cascades the delete to the list's cards and records a DELETE
     * audit row — all atomically.
     * @param data The data for the request.
     * @param data.listId
     * @returns void Successful Response
     * @throws ApiError
     */
    public static Lists_listsDeleteList(data: ListsDeleteListData): CancelablePromise<ListsDeleteListResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/lists/{list_id}',
            path: {
                list_id: data.listId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Copy List
     * Duplicate a list and its cards into the same board (Req 6.6).
     *
     * Delegates to ``BoardListsService.copy_list`` which enforces org-membership
     * (HTTP 403 for non-members), returns HTTP 404 "List not found" when the list
     * does not exist, appends the copy at the end of the same board (title
     * ``"{source} - Copy"``), copies the cards preserving order and records a
     * CREATE audit row — all atomically. Returns the new ``ListPublic``.
     * @param data The data for the request.
     * @param data.listId
     * @returns ListPublic Successful Response
     * @throws ApiError
     */
    public static Lists_listsCopyList(data: ListsCopyListData): CancelablePromise<ListsCopyListResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/lists/{list_id}/copy',
            path: {
                list_id: data.listId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2-compatible password login; returns a bearer access token.
     *
     * The form ``username`` field carries the user's email. On invalid
     * credentials a 401 ``Incorrect email or password`` is raised; otherwise a
     * freshly minted JWT access token is returned with ``token_type="bearer"``.
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static Login_loginLoginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class OrganizationsService {
    /**
     * List Organizations
     * List the organizations the authenticated user is a member of (Req 3.3).
     * @returns OrganizationPublic Successful Response
     * @throws ApiError
     */
    public static Organizations_organizationsListOrganizations(): CancelablePromise<OrganizationsListOrganizationsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/organizations'
        });
    }
    
    /**
     * Create Organization
     * Create an organization owned by the authenticated user.
     *
     * Delegates to ``OrganizationsService.create_org`` which atomically creates the
     * organization plus its owning ``OrganizationMember`` (role ``OWNER``),
     * ``OrgLimit`` (``count`` = 0) and ``OrgSubscription`` rows (Req 3.2, 3.6).
     * Returns the created organization as ``OrganizationPublic`` (camelCase).
     * @param data The data for the request.
     * @param data.requestBody
     * @returns OrganizationPublic Successful Response
     * @throws ApiError
     */
    public static Organizations_organizationsCreateOrganization(data: OrganizationsCreateOrganizationData): CancelablePromise<OrganizationsCreateOrganizationResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/organizations',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Organization
     * Return an organization detail, enforcing org-scoping.
     *
     * Returns the organization when the current user is a member; raises HTTP 403
     * "Not a member of this organization" when they are not (Req 3.4) and HTTP 404
     * when ``org_id`` does not exist (Req 3.5).
     * @param data The data for the request.
     * @param data.orgId
     * @returns OrganizationPublic Successful Response
     * @throws ApiError
     */
    public static Organizations_organizationsGetOrganization(data: OrganizationsGetOrganizationData): CancelablePromise<OrganizationsGetOrganizationResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/organizations/{org_id}',
            path: {
                org_id: data.orgId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Signup
     * Register a new user without authentication.
     *
     * Returns the created user as ``UserPublic`` (no password). Raises HTTP 409
     * "Email already registered" when the email is already taken.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static Users_usersSignup(data: UsersSignupData): CancelablePromise<UsersSignupResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Current User
     * Return the currently authenticated user (``id``, ``email``, ``full_name`` ...).
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static Users_usersReadCurrentUser(): CancelablePromise<UsersReadCurrentUserResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
}