// This file is auto-generated by @hey-api/openapi-ts

export type ActivityLogPublic = {
    id: string;
    workspaceId: string;
    projectId: string;
    taskId?: (string | null);
    actorId: string;
    action: string;
    oldValue?: ({
    [key: string]: unknown;
} | null);
    newValue?: ({
    [key: string]: unknown;
} | null);
    createdAt: string;
    updatedAt: string;
};

export type app__schemas__boards_schema__CardPublic = {
    id: string;
    title: string;
    order: number;
    description?: (string | null);
    listId: string;
    createdAt: string;
    updatedAt: string;
};

export type app__schemas__task_cards_schema__CardPublic = {
    id: string;
    title: string;
    order: number;
    description: (string | null);
    listId: string;
    createdAt: string;
    updatedAt: string;
};

export type AssigneeUpdate = {
    assigneeId: string;
};

export type AttachmentPublic = {
    id: string;
    taskId: string;
    uploaderId: string;
    fileName: string;
    mimeType: string;
    sizeBytes: number;
    createdAt: string;
    updatedAt: string;
    uploader: AuthorPublic;
};

export type AuditLogPublic = {
    id: string;
    orgId: string;
    action: string;
    entityId: string;
    entityType: string;
    entityTitle: string;
    userId: string;
    userImage?: (string | null);
    userName: string;
    createdAt: string;
    updatedAt: string;
};

/**
 * Public attribution for the person who performed/owns a resource.
 */
export type AuthorPublic = {
    id: string;
    fullName?: (string | null);
    avatarUrl?: (string | null);
};

export type BoardCreate = {
    orgId: string;
    title: string;
    imageId?: (string | null);
    imageThumbUrl?: (string | null);
    imageFullUrl?: (string | null);
    imageUserName?: (string | null);
    imageLinkHTML?: (string | null);
};

export type BoardDetail = {
    id: string;
    orgId: string;
    projectId: string;
    title: string;
    imageId?: (string | null);
    imageThumbUrl?: (string | null);
    imageFullUrl?: (string | null);
    imageUserName?: (string | null);
    imageLinkHTML?: (string | null);
    createdAt: string;
    updatedAt: string;
    lists?: Array<ListWithCards>;
};

export type BoardMemberAdd = {
    userId: string;
    role: string;
};

export type BoardMemberPublic = {
    id: string;
    userId: string;
    email: string;
    fullName: (string | null);
    avatarUrl?: (string | null);
    role: string;
    status: string;
    invitedBy?: (string | null);
};

export type BoardMemberRoleUpdate = {
    role: string;
};

export type BoardPublic = {
    id: string;
    orgId: string;
    projectId: string;
    title: string;
    imageId?: (string | null);
    imageThumbUrl?: (string | null);
    imageFullUrl?: (string | null);
    imageUserName?: (string | null);
    imageLinkHTML?: (string | null);
    createdAt: string;
    updatedAt: string;
};

export type BoardUpdate = {
    title?: (string | null);
    imageId?: (string | null);
    imageThumbUrl?: (string | null);
    imageFullUrl?: (string | null);
    imageUserName?: (string | null);
    imageLinkHTML?: (string | null);
};

export type Body_attachments_upload_attachment = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Fixed system-defined statuses; not creatable or editable via any endpoint.
 */
export type CanonicalStatus = 'TODO' | 'IN_PROGRESS' | 'PENDING' | 'DONE';

export type CardCreate = {
    title: string;
    listId: string;
};

export type CardReorder = {
    items: Array<CardReorderItem>;
};

/**
 * A card reorder entry carries the target listId because a card can move across lists.
 */
export type CardReorderItem = {
    id: string;
    order: number;
    listId: string;
};

export type CardUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type ColumnCreate = {
    name: string;
    statusKey: string;
    position?: (number | null);
};

export type ColumnPublic = {
    id: string;
    boardId: string;
    name: string;
    statusKey: string;
    position: number;
    createdAt: string;
    updatedAt: string;
};

export type ColumnReorder = {
    items: Array<ColumnReorderItem>;
};

export type ColumnReorderItem = {
    id: string;
    position: number;
};

export type ColumnUpdate = {
    name?: (string | null);
    statusKey?: (string | null);
    position?: (number | null);
};

export type CommentCreate = {
    content: string;
};

export type CommentPublic = {
    id: string;
    taskId: string;
    userId: string;
    content: string;
    createdAt: string;
    updatedAt: string;
    author: AuthorPublic;
};

export type CommentUpdate = {
    content: string;
};

export type CustomStatusCreate = {
    name: string;
    color?: (string | null);
    canonicalStatus?: (CanonicalStatus | null);
};

export type CustomStatusEmbed = {
    id: string;
    name: string;
    color?: (string | null);
    canonicalStatus?: (string | null);
};

export type CustomStatusPublic = {
    id: string;
    workspaceId: string;
    name: string;
    color: (string | null);
    canonicalStatus: (string | null);
    createdAt: string;
    updatedAt: string;
};

export type CustomStatusUpdate = {
    name?: (string | null);
    color?: (string | null);
    canonicalStatus?: (CanonicalStatus | null);
};

export type EpicCreate = {
    title: string;
    description?: (string | null);
    priority?: (string | null);
    dueDate?: (string | null);
    storyPoint?: (number | null);
};

export type EpicProgressPublic = {
    epicId: string;
    totalTasks: number;
    completedTasks: number;
    storyPointsTotal: number;
    storyPointsCompleted: number;
    completionPercentage: number;
};

export type EpicPublic = {
    id: string;
    projectId: string;
    boardId: string;
    columnId: string;
    title: string;
    description: (string | null);
    priority: string;
    dueDate: (string | null);
    assigneeId: (string | null);
    customStatusId: (string | null);
    position: number;
    type: string;
    storyPoint: (number | null);
    sprintId: (string | null);
    epicId: (string | null);
    createdAt: string;
    updatedAt: string;
};

export type EpicUpdate = {
    title?: (string | null);
    description?: (string | null);
    priority?: (string | null);
    dueDate?: (string | null);
    storyPoint?: (number | null);
};

export type EpicWithTasksPublic = {
    id: string;
    projectId: string;
    boardId: string;
    columnId: string;
    title: string;
    description: (string | null);
    priority: string;
    dueDate: (string | null);
    assigneeId: (string | null);
    customStatusId: (string | null);
    position: number;
    type: string;
    storyPoint: (number | null);
    sprintId: (string | null);
    epicId: (string | null);
    createdAt: string;
    updatedAt: string;
    childTasks?: Array<TaskPublic>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InvitationPublic = {
    membershipId: string;
    scope: 'WORKSPACE' | 'PROJECT';
    workspaceId?: (string | null);
    projectId?: (string | null);
    orgName: string;
    role: string;
    invitedBy?: (string | null);
    createdAt: string;
};

export type scope = 'WORKSPACE' | 'PROJECT';

export type ListCreate = {
    title: string;
    boardId: string;
};

export type ListPublic = {
    id: string;
    title: string;
    order: number;
    boardId: string;
    createdAt: string;
    updatedAt: string;
};

export type ListReorder = {
    boardId: string;
    items: Array<ListReorderItem>;
};

export type ListReorderItem = {
    id: string;
    order: number;
};

export type ListUpdate = {
    title?: (string | null);
    order?: (number | null);
};

export type ListWithCards = {
    id: string;
    title: string;
    order: number;
    boardId: string;
    cards?: Array<app__schemas__boards_schema__CardPublic>;
    createdAt: string;
    updatedAt: string;
};

export type MappingSummary = {
    total: number;
    mapped: number;
    unmapped: number;
    byCanonical?: {
        [key: string]: (number);
    };
};

export type MappingUpdate = {
    canonicalStatus?: (CanonicalStatus | null);
};

export type MemberAdd = {
    userId: string;
    projectRole: string;
};

export type MemberRoleUpdate = {
    projectRole: string;
};

export type NotificationPublic = {
    id: string;
    type: string;
    title: string;
    content?: (string | null);
    metadata?: ({
    [key: string]: unknown;
} | null);
    isRead: boolean;
    createdAt: string;
};

export type OrganizationCreate = {
    name: string;
};

export type OrganizationPublic = {
    id: string;
    name: string;
    createdAt: string;
    updatedAt: string;
};

export type ProjectCreate = {
    name: string;
    key: string;
    description?: (string | null);
};

export type ProjectMemberPublic = {
    id: string;
    userId: string;
    email: string;
    fullName: (string | null);
    avatarUrl?: (string | null);
    projectRole: string;
    status: string;
};

export type ProjectPublic = {
    id: string;
    workspaceId: string;
    name: string;
    key: string;
    description: (string | null);
    createdBy: string;
    createdAt: string;
    updatedAt: string;
};

export type SprintComplete = {
    moveOpenTo?: string;
};

export type SprintCreate = {
    name?: (string | null);
    goal?: (string | null);
    startDate?: (string | null);
    endDate?: (string | null);
};

export type SprintInsights = {
    commitment: {
        [key: string]: unknown;
    };
    workTypes: {
        [key: string]: unknown;
    };
};

export type SprintPublic = {
    id: string;
    projectId: string;
    name: string;
    goal: (string | null);
    status: string;
    startDate: (string | null);
    endDate: (string | null);
    createdAt: string;
    updatedAt: string;
};

export type SprintStart = {
    name?: (string | null);
    goal?: (string | null);
    startDate: string;
    endDate: string;
};

export type SprintUpdate = {
    name?: (string | null);
    goal?: (string | null);
    startDate?: (string | null);
    endDate?: (string | null);
};

/**
 * Sprint list item — includes tasks + kanban status counts.
 */
export type SprintWithTasks = {
    id: string;
    projectId: string;
    name: string;
    goal: (string | null);
    status: string;
    startDate: (string | null);
    endDate: (string | null);
    createdAt: string;
    updatedAt: string;
    tasks?: Array<TaskPublic>;
    todoCount?: number;
    inProgressCount?: number;
    doneCount?: number;
};

export type StoryPointUpdate = {
    storyPoint: number;
};

export type TaskCreate = {
    title: string;
    type?: (string | null);
    parentId?: (string | null);
    dueDate?: (string | null);
    assigneeId?: (string | null);
    storyPoint?: (number | null);
};

export type TaskPublic = {
    id: string;
    projectId: string;
    boardId: string;
    columnId: string;
    title: string;
    description: (string | null);
    priority: string;
    dueDate: (string | null);
    assigneeId: (string | null);
    customStatusId: (string | null);
    customStatus?: (CustomStatusEmbed | null);
    position: number;
    type?: string;
    storyPoint?: (number | null);
    sprintId?: (string | null);
    epicId?: (string | null);
    parentId?: (string | null);
    issueKey?: (string | null);
    createdAt: string;
    updatedAt: string;
};

/**
 * Partial update payload; only explicitly provided fields are applied.
 */
export type TaskUpdate = {
    title?: (string | null);
    description?: (string | null);
    priority?: (string | null);
    dueDate?: (string | null);
    assigneeId?: (string | null);
    customStatusId?: (string | null);
    columnId?: (string | null);
    type?: (string | null);
    storyPoint?: (number | null);
    sprintId?: (string | null);
    epicId?: (string | null);
    parentId?: (string | null);
};

/**
 * Access-token response for a successful login.
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

export type UnreadCountPublic = {
    unreadCount: number;
};

/**
 * API response for a user — never exposes password/hashed_password.
 */
export type UserPublic = {
    id: string;
    email: string;
    fullName?: (string | null);
    isActive: boolean;
    isSuperuser: boolean;
    createdAt: string;
    updatedAt: string;
};

/**
 * Request body for public self-registration (``POST /users/signup``).
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type VelocityConfigPublic = {
    id: string;
    workspaceId: string;
    hoursPerPoint: number;
};

export type VelocityConfigUpdate = {
    hoursPerPoint: number;
};

export type WorkspaceInvite = {
    email: string;
    role: string;
};

export type WorkspaceMemberPublic = {
    id: string;
    workspaceId: string;
    userId: string;
    email: string;
    fullName?: (string | null);
    role: string;
    status: string;
    invitedBy?: (string | null);
    createdAt: string;
    updatedAt: string;
};

export type WorkspaceModeUpdate = {
    mode: string;
};

export type ActivityLogsListTaskActivityData = {
    cursor?: (string | null);
    limit?: number;
    taskId: string;
};

export type ActivityLogsListTaskActivityResponse = (Array<ActivityLogPublic>);

export type ActivityLogsListProjectActivityData = {
    cursor?: (string | null);
    limit?: number;
    projectId: string;
};

export type ActivityLogsListProjectActivityResponse = (Array<ActivityLogPublic>);

export type AttachmentsUploadAttachmentData = {
    formData: Body_attachments_upload_attachment;
    taskId: string;
};

export type AttachmentsUploadAttachmentResponse = (AttachmentPublic);

export type AttachmentsListAttachmentsData = {
    taskId: string;
};

export type AttachmentsListAttachmentsResponse = (Array<AttachmentPublic>);

export type AttachmentsGetAttachmentDownloadUrlData = {
    attachmentId: string;
};

export type AttachmentsGetAttachmentDownloadUrlResponse = ({
    [key: string]: (string);
});

export type AttachmentsDeleteAttachmentData = {
    attachmentId: string;
};

export type AttachmentsDeleteAttachmentResponse = (void);

export type AuditLogsListOrgAuditLogsData = {
    limit?: number;
    orgId: string;
    skip?: number;
};

export type AuditLogsListOrgAuditLogsResponse = (Array<AuditLogPublic>);

export type AuditLogsListBoardAuditLogsData = {
    boardId: string;
};

export type AuditLogsListBoardAuditLogsResponse = (Array<AuditLogPublic>);

export type AuditLogsListCardAuditLogsData = {
    cardId: string;
};

export type AuditLogsListCardAuditLogsResponse = (Array<AuditLogPublic>);

export type BacklogGetBacklogData = {
    projectId: string;
};

export type BacklogGetBacklogResponse = (Array<TaskPublic>);

export type BacklogGetWorkspaceBacklogData = {
    workspaceId: string;
};

export type BacklogGetWorkspaceBacklogResponse = (Array<TaskPublic>);

export type BoardMembersAddMemberData = {
    boardId: string;
    requestBody: BoardMemberAdd;
};

export type BoardMembersAddMemberResponse = (BoardMemberPublic);

export type BoardMembersListMembersData = {
    boardId: string;
};

export type BoardMembersListMembersResponse = (Array<BoardMemberPublic>);

export type BoardMembersChangeRoleData = {
    boardId: string;
    requestBody: BoardMemberRoleUpdate;
    userId: string;
};

export type BoardMembersChangeRoleResponse = (BoardMemberPublic);

export type BoardMembersRemoveMemberData = {
    boardId: string;
    userId: string;
};

export type BoardMembersRemoveMemberResponse = (void);

export type BoardMembersAcceptInvitationData = {
    boardId: string;
};

export type BoardMembersAcceptInvitationResponse = (BoardMemberPublic);

export type BoardMembersDeclineInvitationData = {
    boardId: string;
};

export type BoardMembersDeclineInvitationResponse = ({
    [key: string]: (boolean);
});

export type BoardsCreateBoardData = {
    requestBody: BoardCreate;
};

export type BoardsCreateBoardResponse = (BoardPublic);

export type BoardsListBoardsData = {
    orgId: string;
};

export type BoardsListBoardsResponse = (Array<BoardPublic>);

export type BoardsGetBoardData = {
    boardId: string;
};

export type BoardsGetBoardResponse = (BoardDetail);

export type BoardsUpdateBoardData = {
    boardId: string;
    requestBody: BoardUpdate;
};

export type BoardsUpdateBoardResponse = (BoardPublic);

export type BoardsDeleteBoardData = {
    boardId: string;
};

export type BoardsDeleteBoardResponse = (void);

export type BoardsListBoardTasksData = {
    boardId: string;
};

export type BoardsListBoardTasksResponse = (Array<TaskPublic>);

export type CanonicalStatusesListCanonicalStatusesResponse = (Array<(string)>);

export type CardsCreateCardData = {
    requestBody: CardCreate;
};

export type CardsCreateCardResponse = (app__schemas__task_cards_schema__CardPublic);

export type CardsReorderCardsData = {
    requestBody: CardReorder;
};

export type CardsReorderCardsResponse = (Array<app__schemas__task_cards_schema__CardPublic>);

export type CardsUpdateCardData = {
    cardId: string;
    requestBody: CardUpdate;
};

export type CardsUpdateCardResponse = (app__schemas__task_cards_schema__CardPublic);

export type CardsDeleteCardData = {
    cardId: string;
};

export type CardsDeleteCardResponse = (void);

export type CardsCopyCardData = {
    cardId: string;
};

export type CardsCopyCardResponse = (app__schemas__task_cards_schema__CardPublic);

export type ColumnsListColumnsData = {
    boardId: string;
};

export type ColumnsListColumnsResponse = (Array<ColumnPublic>);

export type ColumnsCreateColumnData = {
    boardId: string;
    requestBody: ColumnCreate;
};

export type ColumnsCreateColumnResponse = (ColumnPublic);

export type ColumnsReorderColumnsData = {
    boardId: string;
    requestBody: ColumnReorder;
};

export type ColumnsReorderColumnsResponse = (Array<ColumnPublic>);

export type ColumnsUpdateColumnData = {
    boardId: string;
    columnId: string;
    requestBody: ColumnUpdate;
};

export type ColumnsUpdateColumnResponse = (ColumnPublic);

export type ColumnsDeleteColumnData = {
    boardId: string;
    columnId: string;
};

export type ColumnsDeleteColumnResponse = (void);

export type ColumnsCreateTaskData = {
    boardId: string;
    columnId: string;
    requestBody: TaskCreate;
};

export type ColumnsCreateTaskResponse = (TaskPublic);

export type CommentsCreateCommentData = {
    requestBody: CommentCreate;
    taskId: string;
};

export type CommentsCreateCommentResponse = (CommentPublic);

export type CommentsListCommentsData = {
    cursor?: (string | null);
    limit?: number;
    taskId: string;
};

export type CommentsListCommentsResponse = (Array<CommentPublic>);

export type CommentsUpdateCommentData = {
    commentId: string;
    requestBody: CommentUpdate;
};

export type CommentsUpdateCommentResponse = (CommentPublic);

export type CommentsDeleteCommentData = {
    commentId: string;
};

export type CommentsDeleteCommentResponse = (void);

export type CustomStatusesCreateCustomStatusData = {
    requestBody: CustomStatusCreate;
    workspaceId: string;
};

export type CustomStatusesCreateCustomStatusResponse = (CustomStatusPublic);

export type CustomStatusesListCustomStatusesData = {
    workspaceId: string;
};

export type CustomStatusesListCustomStatusesResponse = (Array<CustomStatusPublic>);

export type CustomStatusesGetMappingSummaryData = {
    workspaceId: string;
};

export type CustomStatusesGetMappingSummaryResponse = (MappingSummary);

export type CustomStatusesGetCustomStatusData = {
    customStatusId: string;
};

export type CustomStatusesGetCustomStatusResponse = (CustomStatusPublic);

export type CustomStatusesUpdateCustomStatusData = {
    customStatusId: string;
    requestBody: CustomStatusUpdate;
};

export type CustomStatusesUpdateCustomStatusResponse = (CustomStatusPublic);

export type CustomStatusesDeleteCustomStatusData = {
    customStatusId: string;
};

export type CustomStatusesDeleteCustomStatusResponse = (void);

export type CustomStatusesSetCustomStatusMappingData = {
    customStatusId: string;
    requestBody: MappingUpdate;
};

export type CustomStatusesSetCustomStatusMappingResponse = (CustomStatusPublic);

export type EpicsCreateEpicData = {
    projectId: string;
    requestBody: EpicCreate;
};

export type EpicsCreateEpicResponse = (EpicPublic);

export type EpicsListEpicsData = {
    projectId: string;
};

export type EpicsListEpicsResponse = (Array<EpicPublic>);

export type EpicsGetEpicData = {
    epicId: string;
};

export type EpicsGetEpicResponse = (EpicWithTasksPublic);

export type EpicsUpdateEpicData = {
    epicId: string;
    requestBody: EpicUpdate;
};

export type EpicsUpdateEpicResponse = (EpicPublic);

export type EpicsDeleteEpicData = {
    epicId: string;
};

export type EpicsDeleteEpicResponse = (void);

export type EpicsGetEpicProgressData = {
    epicId: string;
};

export type EpicsGetEpicProgressResponse = (EpicProgressPublic);

export type EpicsAddTaskToEpicData = {
    epicId: string;
    taskId: string;
};

export type EpicsAddTaskToEpicResponse = ({
    [key: string]: unknown;
});

export type EpicsRemoveTaskFromEpicData = {
    epicId: string;
    taskId: string;
};

export type EpicsRemoveTaskFromEpicResponse = (void);

export type ListsCreateListData = {
    requestBody: ListCreate;
};

export type ListsCreateListResponse = (ListPublic);

export type ListsReorderListsData = {
    requestBody: ListReorder;
};

export type ListsReorderListsResponse = (Array<ListPublic>);

export type ListsUpdateListData = {
    listId: string;
    requestBody: ListUpdate;
};

export type ListsUpdateListResponse = (ListPublic);

export type ListsDeleteListData = {
    listId: string;
};

export type ListsDeleteListResponse = (void);

export type ListsCopyListData = {
    listId: string;
};

export type ListsCopyListResponse = (ListPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type NotificationsListNotificationsData = {
    cursor?: (string | null);
    limit?: number;
    unread?: boolean;
};

export type NotificationsListNotificationsResponse = (Array<NotificationPublic>);

export type NotificationsGetUnreadCountResponse = (UnreadCountPublic);

export type NotificationsMarkNotificationReadData = {
    notificationId: string;
};

export type NotificationsMarkNotificationReadResponse = (NotificationPublic);

export type NotificationsMarkAllNotificationsReadResponse = ({
    [key: string]: (boolean);
});

export type OrganizationsListOrganizationsResponse = (Array<OrganizationPublic>);

export type OrganizationsCreateOrganizationData = {
    requestBody: OrganizationCreate;
};

export type OrganizationsCreateOrganizationResponse = (OrganizationPublic);

export type OrganizationsGetOrganizationData = {
    orgId: string;
};

export type OrganizationsGetOrganizationResponse = (OrganizationPublic);

export type OrganizationsDeleteOrganizationData = {
    orgId: string;
};

export type OrganizationsDeleteOrganizationResponse = (void);

export type ProjectMembersSearchMembersData = {
    projectId: string;
    /**
     * Search query for name or email
     */
    q?: string;
};

export type ProjectMembersSearchMembersResponse = (Array<ProjectMemberPublic>);

export type ProjectMembersAddMemberData = {
    projectId: string;
    requestBody: MemberAdd;
};

export type ProjectMembersAddMemberResponse = (ProjectMemberPublic);

export type ProjectMembersListMembersData = {
    projectId: string;
};

export type ProjectMembersListMembersResponse = (Array<ProjectMemberPublic>);

export type ProjectMembersChangeRoleData = {
    projectId: string;
    requestBody: MemberRoleUpdate;
    userId: string;
};

export type ProjectMembersChangeRoleResponse = (ProjectMemberPublic);

export type ProjectMembersRemoveMemberData = {
    projectId: string;
    userId: string;
};

export type ProjectMembersRemoveMemberResponse = (void);

export type ProjectMembersAcceptInvitationData = {
    projectId: string;
};

export type ProjectMembersAcceptInvitationResponse = (ProjectMemberPublic);

export type ProjectMembersDeclineInvitationData = {
    projectId: string;
};

export type ProjectMembersDeclineInvitationResponse = ({
    [key: string]: (boolean);
});

export type ProjectsCreateProjectData = {
    requestBody: ProjectCreate;
    workspaceId: string;
};

export type ProjectsCreateProjectResponse = (ProjectPublic);

export type ProjectsGetProjectData = {
    projectId: string;
};

export type ProjectsGetProjectResponse = (ProjectPublic);

export type SprintsCreateSprintData = {
    projectId: string;
    requestBody: SprintCreate;
};

export type SprintsCreateSprintResponse = (SprintPublic);

export type SprintsListSprintsData = {
    projectId: string;
};

export type SprintsListSprintsResponse = (Array<SprintWithTasks>);

export type SprintsGetSprintData = {
    sprintId: string;
};

export type SprintsGetSprintResponse = (SprintPublic);

export type SprintsUpdateSprintData = {
    requestBody: SprintUpdate;
    sprintId: string;
};

export type SprintsUpdateSprintResponse = (SprintPublic);

export type SprintsDeleteSprintData = {
    sprintId: string;
};

export type SprintsDeleteSprintResponse = (void);

export type SprintsStartSprintData = {
    requestBody: SprintStart;
    sprintId: string;
};

export type SprintsStartSprintResponse = (SprintPublic);

export type SprintsCompleteSprintData = {
    requestBody: SprintComplete;
    sprintId: string;
};

export type SprintsCompleteSprintResponse = (SprintPublic);

export type SprintsAddTaskToSprintData = {
    sprintId: string;
    taskId: string;
};

export type SprintsAddTaskToSprintResponse = ({
    [key: string]: unknown;
});

export type SprintsRemoveTaskFromSprintData = {
    sprintId: string;
    taskId: string;
};

export type SprintsRemoveTaskFromSprintResponse = (void);

export type SprintsGetSprintInsightsData = {
    projectId: string;
    sprintId: string;
};

export type SprintsGetSprintInsightsResponse = (SprintInsights);

export type SprintsListWorkspaceSprintsData = {
    workspaceId: string;
};

export type SprintsListWorkspaceSprintsResponse = (Array<SprintWithTasks>);

export type SprintsCreateWorkspaceSprintData = {
    requestBody: SprintCreate;
    workspaceId: string;
};

export type SprintsCreateWorkspaceSprintResponse = (SprintPublic);

export type TasksGetTaskData = {
    taskId: string;
};

export type TasksGetTaskResponse = (TaskPublic);

export type TasksUpdateTaskData = {
    requestBody: TaskUpdate;
    taskId: string;
};

export type TasksUpdateTaskResponse = (TaskPublic);

export type TasksSetAssigneeData = {
    requestBody: AssigneeUpdate;
    taskId: string;
};

export type TasksSetAssigneeResponse = (TaskPublic);

export type TasksUnsetAssigneeData = {
    taskId: string;
};

export type TasksUnsetAssigneeResponse = (TaskPublic);

export type TasksUpdateStoryPointData = {
    requestBody: StoryPointUpdate;
    taskId: string;
};

export type TasksUpdateStoryPointResponse = (TaskPublic);

export type TasksListSubtasksData = {
    taskId: string;
};

export type TasksListSubtasksResponse = (Array<TaskPublic>);

export type UsersSignupData = {
    requestBody: UserRegister;
};

export type UsersSignupResponse = (UserPublic);

export type UsersReadCurrentUserResponse = (UserPublic);

export type VelocityConfigGetVelocityConfigData = {
    workspaceId: string;
};

export type VelocityConfigGetVelocityConfigResponse = (VelocityConfigPublic);

export type VelocityConfigUpdateVelocityConfigData = {
    requestBody: VelocityConfigUpdate;
    workspaceId: string;
};

export type VelocityConfigUpdateVelocityConfigResponse = (VelocityConfigPublic);

export type WorkspaceMembersInviteMemberData = {
    requestBody: WorkspaceInvite;
    workspaceId: string;
};

export type WorkspaceMembersInviteMemberResponse = (WorkspaceMemberPublic);

export type WorkspaceMembersListMembersData = {
    workspaceId: string;
};

export type WorkspaceMembersListMembersResponse = (Array<WorkspaceMemberPublic>);

export type WorkspaceMembersAcceptInvitationData = {
    workspaceId: string;
};

export type WorkspaceMembersAcceptInvitationResponse = (WorkspaceMemberPublic);

export type WorkspaceMembersDeclineInvitationData = {
    workspaceId: string;
};

export type WorkspaceMembersDeclineInvitationResponse = ({
    [key: string]: (boolean);
});

export type WorkspaceMembersListInvitationsData = {
    type?: string;
};

export type WorkspaceMembersListInvitationsResponse = (Array<InvitationPublic>);

export type WorkspaceMembersRemoveMemberData = {
    userId: string;
    workspaceId: string;
};

export type WorkspaceMembersRemoveMemberResponse = (void);

export type WorkspacesSwitchWorkspaceModeData = {
    requestBody: WorkspaceModeUpdate;
    workspaceId: string;
};

export type WorkspacesSwitchWorkspaceModeResponse = (OrganizationPublic);