// This file is auto-generated by @hey-api/openapi-ts

/**
 * Response shape for a card nested under a list (frontend type ``Card``).
 *
 * Serializes to camelCase: ``listId``, ``createdAt``, ``updatedAt``. This is a
 * response-shape definition only; the card table is owned by the task_cards
 * domain (task 15.1).
 */
export type app__schemas__boards_schema__CardPublic = {
    id: string;
    title: string;
    order: number;
    description?: (string | null);
    listId: string;
    createdAt: string;
    updatedAt: string;
};

/**
 * Flat API response for a card (Req 7.7).
 *
 * Serializes to camelCase: ``listId``, ``createdAt``, ``updatedAt``.
 */
export type app__schemas__task_cards_schema__CardPublic = {
    id: string;
    title: string;
    order: number;
    description: (string | null);
    listId: string;
    createdAt: string;
    updatedAt: string;
};

/**
 * API response for an audit log entry.
 *
 * Serializes to camelCase: ``orgId``, ``entityId``, ``entityType``,
 * ``entityTitle``, ``userId``, ``userImage``, ``userName``, ``createdAt``,
 * ``updatedAt`` (requirement 8.6).
 */
export type AuditLogPublic = {
    id: string;
    orgId: string;
    action: string;
    entityId: string;
    entityType: string;
    entityTitle: string;
    userId: string;
    userImage?: (string | null);
    userName: string;
    createdAt: string;
    updatedAt: string;
};

/**
 * Request body for creating a board.
 *
 * Accepts camelCase (``orgId``, ``imageThumbUrl``, ``imageLinkHTML``, ...) and,
 * thanks to ``populate_by_name=True``, the snake_case field names too. Image
 * fields are optional cover-image metadata.
 */
export type BoardCreate = {
    orgId: string;
    title: string;
    imageId?: (string | null);
    imageThumbUrl?: (string | null);
    imageFullUrl?: (string | null);
    imageUserName?: (string | null);
    imageLinkHTML?: (string | null);
};

/**
 * Nested board response for ``GET /boards/{id}`` (Req 5.2).
 *
 * Extends ``BoardPublic`` with ``lists`` ordered by ``order`` ascending, each
 * carrying its ``cards`` ordered by ``order`` ascending. The service is
 * responsible for loading and sorting (design.md section "3. Nested response").
 */
export type BoardDetail = {
    id: string;
    orgId: string;
    title: string;
    imageId?: (string | null);
    imageThumbUrl?: (string | null);
    imageFullUrl?: (string | null);
    imageUserName?: (string | null);
    imageLinkHTML?: (string | null);
    createdAt: string;
    updatedAt: string;
    lists?: Array<ListWithCards>;
};

/**
 * Flat API response for a board (Req 5.7).
 *
 * Serializes to camelCase: ``orgId``, ``imageId``, ``imageThumbUrl``,
 * ``imageFullUrl``, ``imageUserName``, ``imageLinkHTML``, ``createdAt``,
 * ``updatedAt``.
 */
export type BoardPublic = {
    id: string;
    orgId: string;
    title: string;
    imageId?: (string | null);
    imageThumbUrl?: (string | null);
    imageFullUrl?: (string | null);
    imageUserName?: (string | null);
    imageLinkHTML?: (string | null);
    createdAt: string;
    updatedAt: string;
};

/**
 * Request body for updating a board (Req 5.3).
 *
 * All fields are optional so callers can send a partial update (PATCH
 * semantics). Accepts camelCase (``imageThumbUrl``, ``imageLinkHTML``, ...) and,
 * thanks to ``populate_by_name=True``, the snake_case field names too. The
 * service applies only the fields that were explicitly provided
 * (``model_dump(exclude_unset=True)``). ``org_id`` is intentionally absent: a
 * board cannot be moved between organizations.
 */
export type BoardUpdate = {
    title?: (string | null);
    imageId?: (string | null);
    imageThumbUrl?: (string | null);
    imageFullUrl?: (string | null);
    imageUserName?: (string | null);
    imageLinkHTML?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Request body for creating a card.
 *
 * Accepts camelCase (``listId``) and, thanks to ``populate_by_name=True``, the
 * snake_case field names too. ``order`` is NOT accepted from the client — the
 * service derives it as ``max_order(list) + 1`` (Req 7.1).
 */
export type CardCreate = {
    title: string;
    listId: string;
};

/**
 * Request body for ``PATCH /cards/reorder`` (Req 7.4, 7.5, 11.1-11.4).
 *
 * Carries the ``items`` whose ``order`` and ``listId`` should be applied. The
 * service validates that every card (resolved through its current list) and
 * every target ``listId`` belong to the SAME Board before applying all updates
 * in a single transaction.
 */
export type CardReorder = {
    items: Array<CardReorderItem>;
};

/**
 * A single ``{id, order, listId}`` entry of a card reorder payload.
 *
 * Unlike a list reorder entry, a card entry carries the TARGET ``listId``
 * because a card can move across lists (within the same Board) during a
 * reorder (Req 7.4).
 */
export type CardReorderItem = {
    id: string;
    order: number;
    listId: string;
};

/**
 * Request body for ``PATCH /cards/{id}`` (Req 7.2).
 *
 * ``title`` and ``description`` are optional so the client can send a partial
 * update; the service applies only the provided fields.
 */
export type CardUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Request body for creating a list.
 *
 * Accepts camelCase (``boardId``) and, thanks to ``populate_by_name=True``, the
 * snake_case field names too. ``order`` is NOT accepted from the client — the
 * service derives it as ``max_order(board) + 1`` (Req 6.1).
 */
export type ListCreate = {
    title: string;
    boardId: string;
};

/**
 * Flat API response for a list (Req 6.7).
 *
 * Serializes to camelCase: ``boardId``, ``createdAt``, ``updatedAt``.
 */
export type ListPublic = {
    id: string;
    title: string;
    order: number;
    boardId: string;
    createdAt: string;
    updatedAt: string;
};

/**
 * Request body for ``PATCH /lists/reorder`` (Req 6.4, 6.5, 11.1-11.4).
 *
 * Carries the target ``boardId`` and the ``items`` whose ``order`` should be
 * applied. The service validates that every id belongs to ``boardId`` before
 * touching the DB and applies all updates in a single transaction.
 */
export type ListReorder = {
    boardId: string;
    items: Array<ListReorderItem>;
};

/**
 * A single ``{id, order}`` entry of a reorder payload (Req 6.4).
 */
export type ListReorderItem = {
    id: string;
    order: number;
};

/**
 * Request body for ``PATCH /lists/{id}`` (Req 6.2).
 *
 * All fields are optional so the client can send a partial update; the service
 * applies only the provided fields.
 */
export type ListUpdate = {
    title?: (string | null);
    order?: (number | null);
};

/**
 * Response shape for a list with its ordered cards (frontend type ``List``).
 *
 * Serializes to camelCase: ``boardId``, ``createdAt``, ``updatedAt``. ``cards``
 * are expected to be ordered by ``order`` ascending by the service (Req 5.2).
 */
export type ListWithCards = {
    id: string;
    title: string;
    order: number;
    boardId: string;
    cards?: Array<app__schemas__boards_schema__CardPublic>;
    createdAt: string;
    updatedAt: string;
};

/**
 * Request body for creating an organization.
 */
export type OrganizationCreate = {
    name: string;
};

/**
 * API response for an organization.
 *
 * Serializes to camelCase: ``createdAt``, ``updatedAt``.
 */
export type OrganizationPublic = {
    id: string;
    name: string;
    createdAt: string;
    updatedAt: string;
};

/**
 * Access-token response for a successful login.
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * API response for a user — never exposes password/hashed_password.
 *
 * Serializes to camelCase: ``fullName``, ``isActive``, ``isSuperuser``,
 * ``createdAt``, ``updatedAt``.
 */
export type UserPublic = {
    id: string;
    email: string;
    fullName?: (string | null);
    isActive: boolean;
    isSuperuser: boolean;
    createdAt: string;
    updatedAt: string;
};

/**
 * Request body for public self-registration (``POST /users/signup``).
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AuditLogsListOrgAuditLogsData = {
    limit?: number;
    orgId: string;
    skip?: number;
};

export type AuditLogsListOrgAuditLogsResponse = (Array<AuditLogPublic>);

export type AuditLogsListBoardAuditLogsData = {
    boardId: string;
};

export type AuditLogsListBoardAuditLogsResponse = (Array<AuditLogPublic>);

export type AuditLogsListCardAuditLogsData = {
    cardId: string;
};

export type AuditLogsListCardAuditLogsResponse = (Array<AuditLogPublic>);

export type BoardsCreateBoardData = {
    requestBody: BoardCreate;
};

export type BoardsCreateBoardResponse = (BoardPublic);

export type BoardsListBoardsData = {
    orgId: string;
};

export type BoardsListBoardsResponse = (Array<BoardPublic>);

export type BoardsGetBoardData = {
    boardId: string;
};

export type BoardsGetBoardResponse = (BoardDetail);

export type BoardsUpdateBoardData = {
    boardId: string;
    requestBody: BoardUpdate;
};

export type BoardsUpdateBoardResponse = (BoardPublic);

export type BoardsDeleteBoardData = {
    boardId: string;
};

export type BoardsDeleteBoardResponse = (void);

export type CardsCreateCardData = {
    requestBody: CardCreate;
};

export type CardsCreateCardResponse = (app__schemas__task_cards_schema__CardPublic);

export type CardsReorderCardsData = {
    requestBody: CardReorder;
};

export type CardsReorderCardsResponse = (Array<app__schemas__task_cards_schema__CardPublic>);

export type CardsUpdateCardData = {
    cardId: string;
    requestBody: CardUpdate;
};

export type CardsUpdateCardResponse = (app__schemas__task_cards_schema__CardPublic);

export type CardsDeleteCardData = {
    cardId: string;
};

export type CardsDeleteCardResponse = (void);

export type CardsCopyCardData = {
    cardId: string;
};

export type CardsCopyCardResponse = (app__schemas__task_cards_schema__CardPublic);

export type ListsCreateListData = {
    requestBody: ListCreate;
};

export type ListsCreateListResponse = (ListPublic);

export type ListsReorderListsData = {
    requestBody: ListReorder;
};

export type ListsReorderListsResponse = (Array<ListPublic>);

export type ListsUpdateListData = {
    listId: string;
    requestBody: ListUpdate;
};

export type ListsUpdateListResponse = (ListPublic);

export type ListsDeleteListData = {
    listId: string;
};

export type ListsDeleteListResponse = (void);

export type ListsCopyListData = {
    listId: string;
};

export type ListsCopyListResponse = (ListPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type OrganizationsListOrganizationsResponse = (Array<OrganizationPublic>);

export type OrganizationsCreateOrganizationData = {
    requestBody: OrganizationCreate;
};

export type OrganizationsCreateOrganizationResponse = (OrganizationPublic);

export type OrganizationsGetOrganizationData = {
    orgId: string;
};

export type OrganizationsGetOrganizationResponse = (OrganizationPublic);

export type UsersSignupData = {
    requestBody: UserRegister;
};

export type UsersSignupResponse = (UserPublic);

export type UsersReadCurrentUserResponse = (UserPublic);